source "https://rubygems.org"
gem "github-pages", "~> 228", group: :jekyll_plugins
gem "jekyll-theme-hacker", group: :jekyll_plugins
gem "just-the-docs"
gem "minima"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]